when:
  - event: push
    branch: master

steps:
  - name: build-push-web
    image: docker:27-cli
    environment:
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - |
        docker buildx build \
          --file ./apps/web/Dockerfile \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          --cache-from "$DOCKER_USERNAME/web:staging" \
          --cache-from "$DOCKER_USERNAME/web:cache" \
          --tag "$DOCKER_USERNAME/web:staging" \
          --tag "$DOCKER_USERNAME/web:${CI_COMMIT_SHA:0:8}" \
          --push \
          .

      - docker logout